name = "Packwizmods"
author = "Flipper&EyEyron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18638c57ad7c77af14cc6aabf81c44b26ff6fae6d44a262649c398298bb551db"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
