name = "Packwizmods"
author = "Flipper&EyEyron"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a09cad9a8751301d79fb3b3d97abb10f3102037ea0542dbd17e78c83ad4be9b3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
